services:
  - type: web
    name: movie-recommender
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python src/train.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9